Feature/finalized capstone project
Nelofarzabi/Capstone pull request #2
Opened 2023-03-16 08:57 UTC by Nelofarzabi

You should implement this requirements on capstone project  : 
You can use this [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), to implement your project .
The pages should look almost identical to the original design. Small adjustments like text or image changes are acceptable.

You should build only these 2 pages:
     1:The home page.
     2:The about page.

Each of these pages should have versions for 2 different screen sizes:
    1:Mobile: up to 768px wide.
    2:Desktop: 768px or wider.

Interactions:
    Links___
    1:The home page should have a link in the menu to the about page.
    2:The logo in the header links to the home page.

Mobile menu
    1:When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
   2:There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design 
   (colors, typography, spacings, etc.).
   3:The mobile menu should have a close (X) button that closes the menu.

Dynamic page

   1:The section "Featured speakers" should be created dynamically in JavaScript.
  2:You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for 
  this section dynamically.

Here is the Loom video of this project : [Capstone_Project_Loom_Video](https://www.loom.com/share/9f024b0e57d24fc2921734e9f999fca9)

2023-03-16 09:12 UTC, arslanbisharat requested changes
Hi @Nelofarzabi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- The Pull Request has a proper title and description. ✔️
- You have added a descriptive Readme file. Good Job. ✔️
- There is no linter error is present. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please make sure you right descriptive comments. Commenting involves placing Human Readable Descriptions inside of computer programs detailing what the Code is doing. Proper use of commenting can make code maintenance much easier, as well as helping make finding bugs faster. Further, commenting is very important when writing functions that other people will use. :x:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 09:12 UTC, arslanbisharat commented on README.md
> +
- [ ] Thank you for adding a loom video but the video contains a highlight about a piece of the code the student finds interesting or is proud of making.

2023-03-16 09:12 UTC, arslanbisharat commented on README.md
> +Thanks to [Cindy Shin](https://www.behance.net/adagio07). <br>
Good Job giving acknowledgment to the designer.

2023-03-16 09:12 UTC, arslanbisharat commented on about.css
> +#text_color {
- [ ] Let's not use ID as a selector. IDs have a high level of specificity in CSS, meaning that they will override other styles that are applied to the same element using lower-specificity selectors, such as class or tag selectors. This can lead to unexpected styling behavior and make it difficult to maintain a consistent design across the site.

2023-03-16 09:12 UTC, arslanbisharat commented on about.css
> +}
- [ ] Let's not use ID as a selector.

2023-03-16 09:12 UTC, arslanbisharat commented on about.html
> +    <footer class="footer" id="footer_background">
- [ ] [OPTIONAL] The footer size is big compared to the given design. It meets the design requirements but it would be great if you can make it a bit smaller.

2023-03-18 15:27 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Nelofarzabi 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider the following:
- x
- y
- z

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 15:27 UTC, abdulhamiid commented on index.html
> +        <div class="line"></div>
Your Design

![image](https://user-images.githubusercontent.com/78251927/226113730-9cb34d7a-02a0-41ee-acab-4646c15715aa.png)

![image](https://user-images.githubusercontent.com/78251927/226113759-b1d7d644-c0e4-4488-b80a-7e095a924595.png)

![image](https://user-images.githubusercontent.com/78251927/226113798-ddb8d6a3-ac78-4b96-bfdc-2f4d88aa129e.png)

Template
![image](https://user-images.githubusercontent.com/78251927/226113882-95051e48-99ab-4976-9fda-bf97d0c39777.png)

![image](https://user-images.githubusercontent.com/78251927/226113855-8b30ea35-8f82-4963-84e1-fc60d23f7c84.png)

![image](https://user-images.githubusercontent.com/78251927/226113901-90aef375-59cd-469d-8044-5d22533580d6.png)

According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md) we are to follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:

Colors.
Typography: font face, size, and `weight`

Please kindly reduce the thickness of all the lines to match the original design
It is good to follow the project core requirements for professional projects, and if we practice from our learning phase, it will be easier in the future at the industry level. Here is an article on [The importance of understanding software requirements](https://www.freecodecamp.org/news/why-understanding-software-requirements-matter-to-you-as-a-software-engineer/)

2023-03-18 15:27 UTC, abdulhamiid commented on index.html
> +          </ul>
Your Design
![image](https://user-images.githubusercontent.com/78251927/226114742-cacb2ac4-1e7a-4832-a38c-7b4f0e868432.png)

Template (Original design)
![image](https://user-images.githubusercontent.com/78251927/226114777-be868ee7-07da-4fd2-9e70-ba5efe33f4fa.png)

Please kindly adjust the nav links to match the original design

- Arrangement of the Elements
- Color
- Name of the nav-links

2023-03-18 17:46 UTC, abdulhamiid commented
Hi @Nelofarzabi 

I reviewed this your work but I didn't see that there was a review done by a previous reviewer.

So please kindly consider all my requested changes as OPTIONAL

2023-03-18 17:53 UTC, abdulhamiid commented
> Hi @Nelofarzabi,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> * The Pull Request has a proper title and description. ✔️
> * You have added a descriptive Readme file. Good Job. ✔️
> * There is no linter error is present. ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider:
> 
> * [ ]  Please make sure you right descriptive comments. Commenting involves placing Human Readable Descriptions inside of computer programs detailing what the Code is doing. Proper use of commenting can make code maintenance much easier, as well as helping make finding bugs faster. Further, commenting is very important when writing functions that other people will use. ❌
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

👆 Hello next reviewer, 

I reviewed this PR but I didn't see that there was a review already done by a previous reviewer.

Please kindly use the review made by first review er @arslanbisharat and regard all my requested changes as OPTIONAL to be consistent with the First reviewer.

Thanks 😊

2023-03-18 18:49 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @Nelofarzabi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 18:49 UTC, bobb-Rob commented on index.html
> +    <!-- top header end  -->
- [ ] [OPTIONAL] THis top nav bar is not visible. Kindly fix this

2023-03-18 18:49 UTC, bobb-Rob commented on index.html
> +            </li>
- [ ] [OPTIONAL] As mentioned by the previous reviewer, this - About - link item should be first. Kindly fix

2023-03-19 03:24 UTC, merged